#+TITLE: Corona - Anregungen zum Reden
#+SUBTITLE: Aktuelle Version: http://corona.koch.ro
#+OPTIONS: toc:tl author:t creator:nil email:nil
#+LATEX_HEADER: \usepackage[margin=3cm]{geometry}
#+LATEX_HEADER: \usepackage{verse}
#+LATEX_HEADER: \hypersetup{colorlinks=false}

* Vorwort

Diese Zusammenstellung ist nicht vollständig, nicht abgeschlossen und
vielleicht fehlerhaft. Das Ziel dieser Sammlung von Gedanken und Verweisen,
ist es, Menschen zum Gespräch anzuregen.

Der Anlass für die Arbeit an diesem Text war, dass meine Eltern und ich uns zu
einem Gespräch über Corona verabredeten. Sie baten mich, Ihnen doch zur
Vorbereitung die wichtigsten Punkte Zusammenzustellen. Im Gespräch merkten wir
dann, dass wir gar nicht so weit auseinander liegen in unseren Ansichten.

Bei einem Gespräch über Corona ist es wichtig davon auszugehen, dass alle
Gesprächspartner wahrscheinlich gutherzige Menschen sind. Es ist aber gar
nicht so einfach zu erkennen, welche Maßnahmen und Handlungen tatsächlich dem
Guten dienen. Propaganda will immer definieren, was gut und richtig ist und
lässt in dieser Frage keinen Zweifel zu.

Ein großer kommerzieller Propagandaerfolg von Edward Berney war es, Frauen das
Rauchen schmackhaft zu machen. Er nannte Zigaretten die "Fackeln der
Freiheit". Rauchende Frauen seien ein Zeichen der Emanzipation. Im Rückblick
ist es einfacher, Gut von Böse zu unterscheiden.

* Einleitung

Wahrscheinlich hat kein Ereignis seit dem 2. Weltkrieg so viele Mensch auf so
dramatische Weise betroffen, wie die von der Weltgesundheitsorganisation (WHO)
ausgerufene Covid-19 Pandemie. Keine Entscheidung, sei es im großen wie im
privaten kann zur Zeit getroffen werden, ohne die Pandemie und ihre Folgen zu
berücksichtigen.

Viele Menschen leider unter den Schutzmaßnahmen. Das Spektrum reicht von
leichten aber massenweisen beeinträchtigungen des täglichen Lebens, über
zerstörte Existenzen, verschobene dringende Behandlungen, Vereinsamung, Panik
bis zu tatsächlichen Todesfällen durch die Schutzmaßnahmen. Auch die Panik
widerum hat negative Folgen.

Es ist daher berechtigt, sich ein wenig Zeit zu nehmen, über diese Pandemie
nachzudenken.

Auf der anderen Seite gibt es natürlich Todes- oder schwere Krankheitsfälle
von Covid-19. Es ist mir niemand bekannt, der die Existenz des Virus leugnet
und nicht auch bereit ist, Rücksicht auf Risikogruppen zu nehmen. Auch
Angehörige von Verstorbenen verdienen Respekt ihrer Trauer. Covid-19 ist
wahrscheinlich eine schwere Krankheit. Es darf aber nicht vergessen werden,
dass Krankheit, Sterben und Tod zum Leben gehören. Auch die normale Grippe ist
eine schwere Krankheit.

Im folgenden wird das Wort "Pandemie" der Einfachheit halber benutzt, ohne
damit eine Wertung vorwegzunehmen, ob Covid-19 tatsächlich als Pandemie
bezeichnet werden sollte.

* Die Wahrheit suchen

Wissenschaft geht immer davon aus, dass man Wahrheit nicht beweisen kann. Es
ist lediglich möglich, falsche Aussagen zu identifizieren und somit
Falschaussagen zu widerlegen. Eine Theorie, die trotz redlichem Bemühens nicht
widerlegt werden kann und die sich als nützlich herausstellt in dem Sinne,
dass sie Vorhersagen und Erklärungen ermöglicht, wird dann als Annäherung an
die Wahrheit benutzt.

Grundlage aller Erkenntnis ist also der redliche Zweifel.

Neue Erkenntnisse in Wissenschaft und Gesellschaft mussten sich oft gegen den
erbitterten Widerstand der mächtigen Mehrheit durchsetzen.

Es ist mir bewusst, dass Faktenfinder die Legitimität der Berufung auf den
Zweifel bereits in Zweifel ziehen. Die interlektuelle Qualität dieser
Argumentation ist offensichtlich.

* Unvoreingenommenheit

Jedes Nachdenken über die Pandemie steht vor der Herausforderung, sich von der
Übermacht und Eindeutigkeit der vorherrschenden Sichtweise unabhängig zu
machen. Es müssen zwei Fragen streng unabhängig voneinander betrachtet werden:

 1. Gibt es hinreichende Evidenz für eine hochgefährliche Jahrhundertpandemie?
 2. Wenn die Antwort auf den ersten Punkt "Nein" ist, wie kann dann das
    gleichgeschaltete und agressive Handeln und Kommunizieren so vieler
    Akteure erklärt werden?

Falls man diese Fragen nicht voneinander trennt, bleibt man in einem
Zirkelschluß gefangen:

 1. Weil die Pandemie so gefährlich ist, deswegen handeln und reden alle
    gleich.
 2. Alle reden und handeln gleich, deswegen muss die Pandemie gefährlich sein.

* Zweifel

Bevor die beiden Fragen nach der Evidenz und der Erklärung für die
Gleichschaltung beantwortet werden, sollen zunächst Gründe für berechtigten
Zweifel an der offiziellen Geschichte betrachtet werden.

** Vergleich mit anderen Gefahren

Politiker und Medien behaupten, im Interesse der allgemeinen Gesundheit zu
handeln. Jedem kritischen Zeitgenossen fällt aber sofort auf, dass bisherige
Bedrohungen der Gesundheit nicht zu entsprechenden Reaktionen führten.

Nachdenkseiten: [[https://www.nachdenkseiten.de/?p=60198][Den Gesundheitsschutz in den Mittelpunkt stellen? Na, dann
fangen wir doch mal damit an …]]

*** Krankenhauskeime

https://norberthaering.de/die-regenten-der-welt/krankenhauskeime-lockdown

An Krankenhauskeimen sterben nach Informationen des RKI in Deutschland Jahr
für Jahr 10.000 bis 20.000 Menschen:
[[https://www.rki.de/SharedDocs/FAQ/Krankenhausinfektionen-und-Antibiotikaresistenz/FAQ_Liste.html][Antworten auf häufig gestellte Fragen zu Krankenhausinfektionen und Antibiotikaresistenz]]

Tögliche Krankenhauskeime könnten durch Mehrausgaben sowie das Verbot von
Antibiotika in der Tierhaltung bekämpft werden. Im Vergleich zu den Maßnahmen
gegen Corona, sind dies kleine Maßnahmen.

Kommentar von Norbert Häring: [[https://norberthaering.de/die-regenten-der-welt/krankenhauskeime-lockdown][Tote durch Corona, Krankenhauskeime und Tabak:
Hier retten auf Teufel komm raus, da Achselzucken]]

Siehe auch: [[https://www.aerzte-gegen-massentierhaltung.de][Ärzte gegen Massentierhaltung e.V.]]

*** Rauchen

- Das tödlichste Artefakt https://www.nachdenkseiten.de/?p=48256
- Das tödlichste Artefakt – Gedanken zu Robert Proctors Buch über die
  Zigarettenkatastrophe https://www.nachdenkseiten.de/?p=47523
- Hauptsache nikotinabhängig. Über die Gesundheitsgefahren des Tabakrauchens
  und des Gebrauchs von E-Inhalationsprodukten und Tabakerhitzern.
  https://www.nachdenkseiten.de/?p=44820

*** Alkohol

Alkoholmissbrauch wird nicht konsequent bekämpft. Stattdessen gibt es
Alkopops.

WHO: "In 2016, the harmful use of alcohol resulted in some 3 million deaths
(5.3% of all deaths) worldwide" - [[https://apps.who.int/iris/bitstream/handle/10665/274603/9789241565639-eng.pdf?ua=1][Global status report on alcohol and health
2018]]

*** Feinstaub

Deutsche Welle: "Feinstaub, Stickstoffdioxid, bodennahes Ozon und andere
Luftschadstoffe haben im Jahr 2016 mehr als 400.000 vorzeitige Todesfälle in
Europa verursacht." - [[https://www.dw.com/de/studie-feinstaub-f%C3%BChrt-zu-zahlreichen-vorzeitigen-todesf%C3%A4llen/a-50855047][Studie: Feinstaub führt zu zahlreichen vorzeitigen
Todesfällen]].

*** Pflegenotstand

Pflegenotstand herrscht seit Jahren. Außer Beifall zu klatschen ist auch in
Folge der "Pandemie" nichts geschehen. Dabei war die drohende Überlastung des
Gesundheitssystems das Hauptargument für die Maßnahmen: "Flatten the
curve". Spätestens im April hätte es Notfallprogramme geben müssen zur
Ausbildung von Pflegehelfern und zur Anwerbung bereits ausgebildeter
Pflegekräfte.

Statt in diesem Bereich Notstände zu beseitigen, werden angeblich
unverantwortliche Maskenverweigerer oder feiernde Jugendliche diffamiert.

Gerade dieser Bereich zeigt deutlich, dass der Schutz der Bevölkerung nicht
das Hauptmotiv der Maßnahmen sein kann.

André Tautenhahn auf TauBlog.de, 3.11.2020: [[https://www.taublog.de/201103der-karren-wird-seit-jahren-vor-die-wand-gefahren][Der Karren wird seit Jahren vor
die Wand gefahren]] - "[...] die Höchstarbeitszeit für Beschäftigte in Kliniken
und Pflegeheimen erneut auf bis zu 60 Stunden pro Woche erhöht."

Nachdenkseiten, 3.11.2020: [[https://www.nachdenkseiten.de/?p=66470][Personalengpass auf den Intensivstationen – das
Versagen der Politik wird abgewälzt]].

*** Zivilisationskrankheiten: Diabetes, Übergewicht, Bluthochdruck

Wichtigste Todesursachen in Industriestaaten nach Manfred Spitzer: Diabetes,
Übergewicht, Bluthochdruck. Wird etwas gegen Zucker getan?

Interessant ist, dass die Bill und Melinda Gates Foundation (BMGF) mindestens
bis 2015 über 2 Milliarden US-Dollar in Coca-Cola und McDonald's investierte:
[[https://philanthropynewsdigest.org/news/gates-foundation-divests-from-mcdonald-s-coca-cola-exxon][Gates Foundation Divests From McDonald's, Coca-Cola, Exxon]].

*** Digitalisierung und Kinder

Die Folgen des Digitalkonsums sind gravierend, werden aber nicht bekämpft
sondern noch durch Steuergelder unterstützt, siehe Manfred Spitzer. Dies
zeigt auch, dass die Digitalkonzerne, die sich jetzt mit Apps als Helfer
gegen das Virus andienen, nicht an der Gesundheit der Bevölkerung
interessiert sind.

Nachdenkseiten: [[https://www.nachdenkseiten.de/?p=49485][Der Digitalpakt wird unseren Kindern sehr schaden. Eigentlich
unverantwortlich.]]

** Glaubwürdigkeit der Protagonisten

*** Correctiv

Correctiv ist eine Faktenchecker Organisation, die z.B. für Facebook
entscheidet, was wahr und unwahr ist. Zum Thema Corona ist für Correctiv alles
unwahr, was der WHO oder der Bundeskanzlerin widerspricht.

Auf der [[https://correctiv.org/ueber-uns][Über uns]] Seite von Correctiv findet man unter Zuwendungen und dann
noch ein Klick, um "Zuwendungen nach Jahren" aufzuklappen, die Hauptgeldgeber:

- Luminate – Omidyar Network Foundation. Stiftung des eBay Gründers Pierre
  Omidyar, ein großspender der Demokratischen Partei in den USA. Omidyar ist
  auch Geldgeber der Zeitung "The Intercept". Der Journalist Glenn Greenwald
  hat sich vom Intercept getrennt nachdem dieser einen kritischen Artikel über
  Joe Biden nicht veröffentlichte.
- Schöpflin Stiftung - Badische Unternehmerfamilie
- Stiftung Mercator GmbH - Duisburger Unternehmerfamilie (Metro)
- Deutsche Telekom
- Rudolf Augstein Stiftung
- Open Society Stiftung - George Soros
- Brost-Stiftung - Anneliese Brost, WAZ-Mediengruppe
- DNI - Hier wird nur die Abkürzung angegeben. Wahrscheinlich ist hier das
  [[https://de.wikipedia.org/wiki/Director_of_National_Intelligence][Director of National Intelligence]], ein Zusammenschluß der US-Geheimdienste
  gemeint.
- Bundeszentrale für politische Bildung, also eine Einrichtung der Deutschen
  Regierung
- Konrad Adenauer Stiftung, RTL Television GmbH, Deutsche Bank AG, Facebook,
  Google mit kleineren Beträgen

[[https://meinungsfreiheit.steinhoefel.de/2020/10/29/fall-35-achse-des-guten-triumphiert-ueber-correctiv-oberlandesgericht-karlsruhe-untersagt-rechtswidrigen-faktencheck][Fall 35: „Achse des Guten“ triumphiert über Correctiv: Oberlandesgericht
Karlsruhe untersagt rechtswidrigen „Faktencheck“]]

*** Bill Gates

- 2016-01-31, Telepolis: [[https://www.heise.de/tp/features/Bill-Gates-zwischen-Schein-und-Sein-3378037.html][Bill Gates zwischen Schein und Sein]]
- 19.12.2018, Netfrauen.org: [[https://netzfrauen.org/2018/12/19/who/][Ein gefährliches Netzwerk und unsägliche Allianz
  – Bill Gates und die WHO]]
- 2019. FR: [[https://www.fr.de/wirtschaft/privatisierung-weltrettung-11077887.html][Die Privatisierung der Weltrettung]]
- 2020-05-23, finanzmarktwelt: [[https://finanzmarktwelt.de/bill-gates-stiftung-in-der-kritik-wie-gesund-ist-seine-macht-faktencheck-168318][Bill Gates Stiftung in der Kritik: Wie gesund
  ist seine Macht? Faktencheck]]

*** Christian Drosten

Drosden zur Schweinegrippe 2009: "Es gebe eine dramatische Zunahme der
Erkrankungen in Süddeutschland, stellte der Leiter des Instituts für Virologie
der Universitätsklinik Bonn, Prof. Christian Drosten, am Montag (02.11.2009)
fest. Er gehe davon aus, dass die Grippewelle in etwa fünf bis sechs Wochen
über den restlichen Teil des Landes hinwegziehen werde." - Deutsche Welle,
[[https://www.dw.com/de/schweinegrippe-auf-dem-vormarsch/a-4850220][Schweinegrippe auf dem Vormarsch]]

*** Neil Ferguson

Nachdenkseiten: [[https://www.nachdenkseiten.de/?p=66244][Corona und gekaufte Wissenschaft – Wie falsche Wissenschaft
die Welt in einen Abgrund stürzt]].

Ferguson sagte im März 550.000 Tote für Großbritannien, 2,2 Millionen für die
USA und 85.000 für Schweden voraus. Dies ist auch in Schweden nicht
eingetreten. Ferguson hat sich selber nicht an Ausgangsbeschränkungen
gehalten. Das Imperial College London wo er arbeitet erhielt seit 2010 190
Millionen US-Dollar von der BMGF.

*** Karl Lauterbach

[[https://www.welt.de/politik/deutschland/article218800984/Corona-Regeln-Lauterbach-fordert-Kontrollen-in-Privatwohnungen.html][Lauterbach fordert Kontrollen in Privatwohnungen]]

*** Wikipedia

TODO: Wikipedia ist nicht glaubwürdig. Siehe z.B. "Neues aus Wikihausen".

** Art der Kommunikation

- Diffamierung
- Unlaute Methoden, z.B. Vergleich mit Chemtrails, Echsenmenschen
- Keine saubere Verwendung von Begriffen: Testpositiv, infiziert, krank
- Absolutzahlen
- Massive Zensur auf YouTube
  - https://nypost.com/2020/05/16/youtube-censors-epidemiologist-knut-wittkowski-for-opposing-lockdown
*** Strafen statt diskutieren
**** Dr. Friedrich Pürner, Leiter Gesundheitsamt, Strafversetzt

Anfang November, merkur.de: [[https://www.merkur.de/bayern/coronavirus-bayern-markus-soeder-friedrich-puerner-gesundheitsamt-kritik-strategie-strafe-beamter-zr-13922061.html][Er kritisierte öffentlich Söders Corona-Politik:
Gesundheitsamt-Chef wird strafversetzt]]

Friedrich Pürner ist Facharzt, Epidemiologe und Chef des Gesundheitsamts
Aichach-Friedberg bei Augsburg.

*** Manipulation

Aus "Wie-soll-es-weitergehen": "Die Medien nutzen auch die Macht der Bilder
und setzen diese gezielt ein. Sie schockieren uns mit Aufnahmen von
angeblichen Corona-Massengräbern in den USA, verschweigen aber gleichzeitig,
dass verstorbene Obdachlose dort bereits seit vielen Jahren in Sammelgräbern
bestattet werden und entsprechende Videoaufnahmen bereits 2016 entstanden
sind. Sie zeigen uns dramatische Bilder von Militär-LKWs, die Särge im
norditalienischen Bergamo abtransportieren und unterschlagen gleichzeitig die
wichtige Information, dass laut dem Dachverband der italienischen
Bestattungsbranche zu Beginn der Coronakrise 70 Prozent der
Bestattungsunternehmen in der Region quarantänebedingt ihre Arbeit
niederlegten und nur deswegen das Militär für einen einmaligen Transport von
60 Särgen herangezogen wurde."

TODO: Quellen für den Absatz oben prüfen!

- The Potter´s Field; www.youtube.com; 2016
- Coronavirus, Federazione Onoranze Funebri; www.adnkronos.com; 24.03.2020

Daniele Ganser beschreibt einige Techniken der Manipulation am 11.9.: [[https://www.youtube.com/watch?v=3gertJ5VFfM][Corona
und die Medien]], wie z.B.:

- Verwendung absoluter Zahlen oder Bezug
- Gleichsetzung von Testpositiven mit Infizierten mit Hospitalisierten
- Verwendung von suggestiven Bildern, teilweise ohne Bezug zur Meldung
- Verschweigen von beruhigenden Informationen
- Deklaration von Toten Verstorbenen Covid-Tote trotz abweichender oder
  unbekannter Todesursache

*** Panikpapier aus Deutschland und Österreich

 Ein internes Strategiepapier des Deutschen Bundesinnenministerium erklärt
 ([[https://www.abgeordnetenwatch.de/blog/informationsfreiheit/das-interne-strategiepapier-des-innenministeriums-zur-corona-pandemie][abgeordnetenwatch.de]]), dass eine "Schockwirkung" beabsichtigt sei:

 "Um die gewünschte Schockwirkung zu erzielen, müssen die konkreten
 Auswirkungen einer Durchseuchung auf die menschliche Gesellschaft verdeutlicht
 werden:

 1. Viele Schwerkranke werden von ihren Angehörigen ins Krankenhaus gebracht,
    aber abgewiesen, und sterben qualvoll um Luft ringend zu Hause. [...]

 2. [...] Wenn sie [Die Kinder] dann ihre Eltern anstecken, und einer davon
    qualvoll zu Hause stirbt und sie das Gefühl haben, Schuld daran zu sein,
    weil sie z.B. vergessen haben, sich nach dem Spielen die Hände zu waschen,
    ist es das Schrecklichste, was ein Kind je erleben kann.

 3. Folgeschäden: [...]"

Auch in Österreich ist Angst anscheinend bewusst als Mittel eingesetzt worden:

- meinbezirk.at: [[https://www.meinbezirk.at/wieden/c-politik/bevoelkerung-soll-angst-vor-ansteckung-haben_a4046607][Bevölkerung soll "Angst vor Ansteckung" haben]]
- Die Presse: [[https://www.diepresse.com/5805870/regierungsprotokoll-angst-vor-ansteckung-erwunscht][Regierungsprotokoll: Angst vor Ansteckung erwünscht?]]

** PCR Tests

Drosten hat seinen PCR Test entwickelt ohne eine Probe des Virus zu haben. Er
nahm stattdessen aus seiner Datenbank typische Genfragmente eines Coronavirus,
entwickelte für diesen einen Test und schickte den Test nach Wuhan. Weil der
Test bei Patienten in Wuhan positiv war, behauptete er, dass der Test geeignet
sei, das neue SARS CoV-2 Virus nachzuweisen.

Er behauptet, dass dieses Verfahren gerechtfertigt sei, weil seit Jahren keine
SARS Viren mehr bei Menschen zirkulieren würden.

Das Virus ist bis heute von niemandem isoliert worden.

- 97% falsche Testergebnisse durch das MVZ Labor seit April 2020
  https://www.youtube.com/watch?v=cFAq8CqN1Gg
- Drosten 2014, [[https://www.wiwo.de/technologie/forschung/virologe-drosten-im-gespraech-2014-die-who-kann-nur-empfehlungen-aussprechen/9903228-2.html][Wirtschaftwoche]], PCR Tests viel zu empfindlich: "Ja, aber die
  Methode ist so empfindlich, dass sie ein einzelnes Erbmolekül dieses Virus
  nachweisen kann. Wenn ein solcher Erreger zum Beispiel bei einer
  Krankenschwester mal eben einen Tag lang über die Nasenschleimhaut huscht,
  ohne dass sie erkrankt oder sonst irgend etwas davon bemerkt, dann ist sie
  plötzlich ein Mers-Fall. Wo zuvor Todkranke gemeldet wurden, sind nun
  plötzlich milde Fälle und Menschen, die eigentlich kerngesund sind, in der
  Meldestatistik enthalten. Auch so ließe sich die Explosion der Fallzahlen in
  Saudi-Arabien erklären. Dazu kommt, dass die Medien vor Ort die Sache
  unglaublich hoch gekocht haben."
- Es ist nicht klar, mit welchen Verfahren und Parametern getestet wird. Jedes
  Labor macht sein eigenes Testverfahren.
  https://correctiv.org/faktencheck/2020/07/02/nein-die-who-empfahl-keine-voellig-unspezifischen-corona-tests
- PCR Tests sind für Diagnosen nicht zugelassen.
- Es wird mit viel zu hoher Sensibilität getestet, z.B. [[https://www.bioscientia.de/home/aktuelles/2020/07/was-bedeuten-die-begriffe-dual-target-pcr-und-ct-wert][bioscientia]]
  - "Nach unseren Erfahrungen beurteilen wir daher auch den isolierten
    Nachweis eines einzelnen Gens je nach Spezifität als positiv für
    SARS-CoV-2, empfehlen aber bei unklaren Fällen eine Kontrolle."  "Wir
    empfehlen, weitere Maßnahmen unabhängig vom Ct-Wert einzuleiten."

** Keine ausreichende Diskussion

Das Land Bayern hat keine Akten über die Grundlagen der Verordnungen:
https://www.heise.de/tp/features/Bayerische-Regierung-hat-angeblich-keine-Akten-zu-Corona-Beschluessen-4903549.html
https://www.ckb-anwaelte.de/corona-update-17-august-2020

*** Experten

Folgende Experten würden gerne an einer öffentlichen Debatte mitwirken und
bekommen diese Möglichkeit nicht.

- [[https://de.wikipedia.org/wiki/Sucharit_Bhakdi][Dr. Sucharit Bhakdi]] - Facharzt für Mikrobiologie und Infektionsepidemiologie
  und ehem. Leiter des Instituts für Medizinische Mikrobiologie und Hygiene,
  Autor des Spiegel Bestsellers "Corona Fehlalarm?"
- Dr Joel Kettner, Prof. of Community Health Sciences and Surgery at
  University of Manitoba
- Dr. Yoram Lass - ehem. Generaldirektor des Israelitischen
  Gesundheitsministeriums
- [[https://de.wikipedia.org/wiki/Pietro_Vernazza][Prof. Dr. med. Pietro Vernazza]] - Chefarzt der Infektiologie beim
  Kantonsspital St. Gallen
- [[https://de.wikipedia.org/wiki/Hendrik_Streeck][Prof. Hendrik Streeck]] - Professor für Virologie und Direktor des Institutes
  für Virologie und HIV-Forschung an der Medizinischen Fakultät der
  Universität Bonn
- Dr Yanis Roussel et al - Studienautor [[https://www.researchgate.net/publication/340046331_SARS-CoV-2_fear_versus_data][SARS-CoV-2: fear versus data]]
- [[https://en.wikipedia.org/wiki/David_L._Katz][Dr. David L. Katz]] - Mitunterzeichner der "Great Barrington Declaration"
- [[https://en.wikipedia.org/wiki/Michael_Osterholm][Prof. Michael Osterholm]] - Epidemiologe, Direktor des Center for Infectious
  Disease Research and Policy an der University of Minnesota
- [[https://de.wikipedia.org/wiki/Peter_C._G%C3%B8tzsche][Prof. Peter C. Gøtzsche]] - Professor für klinisches Forschungsdesign und
  Analyse, Mitbegründer der Cochrane Collaboration
- [[https://de.wikipedia.org/wiki/Sunetra_Gupta][Prof. Dr. Sunetra Gupta]] - Professorin der Epidemiologie
- [[https://de.wikipedia.org/wiki/Anders_Tegnell][Anders Tegnell]] - Staatsepidemiologe der schwedischen Behörde für öffentliche
  Gesundheit
- Dr. Pablo Goldschmidt, Professor of Molecular Pharmacology at the
  Université Pierre et Marie Curie in Paris
- [[https://profiles.stanford.edu/eran-bendavid][Prof. Dr Eran Bendavid]] - Prof. für Medizin und öffentliche Gesundheit,
  Stanford
- [[https://healthpolicy.fsi.stanford.edu/people/jay_bhattacharya][Prof. Dr. Jay Bhattacharya]], Stanford
- [[https://en.wikipedia.org/wiki/Tom_Jefferson_(epidemiologist)][Tom Jefferson]] - Epidemiologe, Berater der Italienischen Staatsagentur für
  regionale Gesundheitsdienste
- [[https://de.wikipedia.org/wiki/Michael_Levitt][Michael Levitt]] - Nobelpreisträger für Chemie
- [[https://en.wikipedia.org/wiki/John_Oxford][Prof. John Oxford]] - Virologe, führender Experte für Grippe
- [[https://vitalstoff.blog/tag/knut-m-wittkowski][Prof. Dr. Knut Wittkowski]] - ehem. Leiter der Abteilung für Biostatistik,
  Epidemiologie und Forschungsdesign an der Rockefeller-Universität
- [[https://de.wikipedia.org/wiki/Klaus_P%C3%BCschel][Prof. Dr. Klaus Püschel]] - Professor für Rechtsmedizin
- [[https://de.wikipedia.org/wiki/Alexander_S._Kekul%C3%A9][Dr. Alexander S. Kekulé]] - Lehrstuhl für Medizinische Mikrobiologie und
  Virologie an die Martin-Luther-Universität Halle-Wittenberg
- Dr. med. Claus Köhnlein, Internist, Autor des Buches "Virus-Wahn" (2009)
- [[https://de.wikipedia.org/wiki/G%C3%A9rard_Krause][Prof. Dr. Gérard Krause]] - Leiter der Abteilung Epidemiologie am
  Helmholtz-Zentrum für Infektionsforschung in Braunschweig
- [[https://de.wikipedia.org/wiki/Gerd_Gigerenzer][Prof. Dr. Gerd Gigerenzer]] - Psychologe, kritisiert die Panikmache
- [[https://de.wikipedia.org/wiki/Beda_M._Stadler][Prof. Dr. Beda M. Stadler]] - Molekularbiologe sowie emeritierter Professor
  und ehemaliger Direktor des Instituts für Immunologie der Universität Bern
- [[https://de.wikipedia.org/wiki/Stefan_Hockertz][Dr. Stefan Hockertz]] - ehem. Direktor des Instituts für Experimentelle und
  Klinische Pharmakologie und Toxikologie am Universitätskrankenhaus Eppendorf

Die Ursprüngliche Liste der oben genannten Experten stammt aus Listen der
Webseite [[https://off-guardian.org/category/covexperts][off Guardian]]. Dort findet man auch Hinweise auf die verschiedenen
Formen des Drucks, der auf Experten ausgeübt wurde anstatt mit ihnen zu
debatieren.

**** Dr. John Ioannidis

[[https://de.wikipedia.org/wiki/John_Ioannidis][John Ioannidis]] Professor für Medizin und Professor für Epidemiologie und
Bevölkerungsgesundheit an der Stanford University School of Medicine, sowie
professor by courtesy für biomedizinische Datenwissenschaft an der Stanford
University School of Medicine, professor by courtesy für Statistik an der
Stanford University School of Humanities and Sciences, und Kodirektor des
Innovationszentrum für Meta-Forschung in Stanford, ebenfalls Stanford
University School of Medicine. Er gehört zu den meist-zitierten
Wissenschaftlern weltweit.

Sterblichkeitsrate maximal 0,31% mit großen regionalen Unterschieden
https://www.who.int/bulletin/online_first/BLT.20.265892.pdf
https://www.heise.de/tp/features/Ioannidis-Mehr-als-500-Millionen-sollen-bereits-mit-Covid-19-infiziert-gewesen-sein-4938011.html

**** Wolfgang Wodarg

Prof. Dr. Martin Schwab, Juraprofessor Bielefeld hat ein umfangreiches [[http://www.jura.uni-bielefeld.de/lehrstuehle/schwab/Prof.-Schwab-zu-Wodarg.pdf][Dosier]]
zur Verteidigung von Herrn Wodarg erstellt. Das Dossier enthält auch Analysen,
welche Aussagen von Wodarg nach jetzigem Wissensstand als belegt angesehen
werden können.

Nach Wodarg eignet sich die Grippe in jedem Jahr, um eine Pandemie auszurufen:
[[https://www.youtube.com/watch?v=jKaRvpTW8sE][Wodarg: Industrieverbände bestimmen, ob man eine Pandemie ausruft (2013)]]

*** Positionspapiere, Gruppen, Verbände

TODO: [[https://de.wikipedia.org/wiki/Great-Barrington-Erkl%C3%A4rung][Great Barrington Declaration]]

**** 2020-04-14 Aerzte/innen mit blick aufs ganze (AMBAG)

Positionspapier dokumentier im Film "Unerhört!", 25:00. Forderung nach
Lockerungen des Lockdowns. Unterschrieben von 89 namentlich genannten Ärzten,
21 anoynmen Unterzeichnenden.

Nur ein Schweizer Medium berichtet:
https://www.tagesanzeiger.ch/die-gefahr-fuer-die-patienten-wird-immer-groesser-954912313492

**** 2020-05-07 EIN AUFRUF FÜR DIE KIRCHE UND FÜR DIE WELT

https://veritasliberabitvos.info/aufruf

"Die Fakten haben gezeigt, dass unter dem Vorwand der Covid-19-Epidemie in
vielen Fällen unveräußerliche Rechte der Bürger verletzt und ihre
Grundfreiheiten unverhältnismäßig und ungerechtfertigt eingeschränkt werden
[...]. Die öffentliche Gesundheit darf und kann kein Alibi werden, um die
Rechte von Millionen von Menschen auf der ganzen Welt zu verletzen
[...]. Viele maßgebliche Stimmen aus der Welt der Wissenschaft und der Medizin
bestätigen, dass der Alarmismus der Medien wegen Covid-19 in keiner Weise
gerechtfertigt zu sein scheint.

[...]

Das Auferlegen dieser unfreiheitlichen Maßnahmen ist ein beunruhigendes
Vorspiel zur Schaffung einer Weltregierung, die sich jeder Kontrolle
entzieht."

Der Aufruf ist nicht nur von hohen katholischen Würdenträgern [[https://veritasliberabitvos.info/signatories][unterzeichnet]]
sondern auch von Journalisten, Medizinern, Rechtsanwälten und
Wissenschaftlern. Offizielle katholische Institutionen [[https://de.wikipedia.org/wiki/Carlo_Maria_Vigan%C3%B2#Verschw%C3%B6rungsmythen_zur_Corona-Krise][distanzieren]] sich von
dem Aufruf.

**** 2020-09-05 Doktoren für offene Debatte (Belgien)

Titel [[https://docs4opendebate.be/de/offener-brief][Offener Brief von Ärzten und Fachleuten aus dem Gesundheitsbereich an
alle belgischen Behörden und alle belgischen Medien]].

Unterschrieben von 673 medizinischen Doktoren, 2187 ausgebildeten
Gesundheitsmitarbeitern und 16781 Bürgern. Die Webseite enthält Links zu
ähnlichen Initiativen aus anderen Ländern.

**** 2020-09-08 COVID-19: Wo ist die Evidenz?

https://www.ebm-netzwerk.de/de/veroeffentlichungen/covid-19

"Die mediale Berichterstattung sollte unbedingt die von uns geforderten
Kriterien einer evidenzbasierten Risikokommunikation beherzigen und die
irreführenden Meldungen von Absolutzahlen ohne Bezugsgröße beenden.

[...]

Es gibt insgesamt noch sehr wenig belastbare Evidenz, weder zu COVID-19 selbst
noch zur Effektivität der derzeit ergriffenen Maßnahmen, aber es ist nicht
auszuschließen, dass die trotz weitgehend fehlender Evidenz ergriffenen
Maßnahmen inzwischen größeren Schaden anrichten könnten als das Virus
selbst. Jegliche Maßnahmen sollten entsprechend wissenschaftlich begleitet
werden, um den Nutzen und Schaden bzw. das Verhältnis von Nutzen und Schaden
zu dokumentieren."

**** 2020-10-28 Positionspapier von Wissenschaft und Ärzteschaft zur Strategieanpassung im Umgang mit der Pandemie

https://www.kbv.de/html/48910.php

Zusammenfassung der Kernthesen

- Abkehr von der Eindämmung alleine durch Kontaktpersonennachverfolgung.
- Einführung eines bundesweit einheitlichen Ampelsystems anhand dessen sowohl
  auf Bundes- als auch auf Kreisebene die aktuelle Lage auf einen Blick
  erkennbar wird.
- Fokussierung der Ressourcen auf den spezifischen Schutz der
  Bevölkerungsgruppen, die ein hohes Risiko für schwere Krankheitsverläufe
  haben.
- Gebotskultur an erste Stelle in die Risikokommunikation setzen.

"Der Rückgang der Fallzahlen ist politisch zwar eine dringende Aufgabe, aber
nicht um jeden Preis. Wir erleben bereits die Unterlassung anderer dringlicher
medizinischer Behandlungen, ernstzunehmende Nebenwirkungen bei Kindern und
Jugendlichen durch soziale Deprivation und Brüche in Bildungs- und
Berufsausbildungsgängen, den Niedergang ganzer Wirtschaftszweige, vieler
kultureller Einrichtungen und eine zunehmende soziale Schieflage als Folge."

BETEILIGTE

- Kassenärztliche Bundesvereinigung
- Prof. Hendrik Streeck, Direktor des Instituts für Virologie der Universität
  Bonn
- Prof. Jonas Schmidt-Chanasit, Leiter der Abteilung Arbovirologie am
  Bernhard-Nocht-Institut für Tropenmedizin in Hamburg

Unterstützt von 30 Verbänden und Vereinen.

** Prominente Kritiker, aber keine Experten

*** Heribert Prantl

2.11.2020, SZ: Corona-Maßnahmen - Die Grenzen des Erträglichen. [[https://www.sueddeutsche.de/politik/corona-massnahmen-die-grenzen-des-ertraeglichen-1.5100174][Videokommentar
von Heribert Prantl]].

*** David Claudio Siber
Grünenpolitiker aus Flensburg, wurde aus der Ratsfraktion ausgeschlossen
nachdem er auf der Demonstration in Berlin gesprochen hat. Er hat versucht
innerhalb der Grünen Partei ein offene Diskussion zu bewirken. Er erfuhr auch,
dass die Grüne Bundestagsfraktion sich ausschließlich von Drosten über Corona
informieren ließ und keine zweite Meinung einholte.

https://www.ndr.de/nachrichten/schleswig-holstein/coronavirus/Nach-Corona-Demo-Flensburgs-Gruenen-Politiker-Siber-wehrt-sich,siber100.html

https://david-claudio-siber.de/studien

*** Thomas Berthold

https://www.youtube.com/watch?v=3p41XxbwZP0
https://www.youtube.com/watch?v=lO3-SKBu6VM
https://www.swr.de/sport/fussball/thomas-berthold-corona-skeptiker-100.html

Bild-Zeitung kündigt Zusammenarbeit nach Rede auf Demo in
Berlin. Wikipedia-Artikel wird verändert und bezeichnet Berthold als
Antisemiten.

Er erlebt aber viele Zustimmung von Menschen die ihn auf der Straße
ansprechen.

*** Wolfgang Kubicki

2020-10-29 „Der Lockdown light atmet einen undemokratischen Geist“

https://www.tagesspiegel.de/politik/neue-corona-regeln-der-lockdown-light-atmet-einen-undemokratischen-geist/26567648.html

*** Robert F. Kennedy

Neffe von JFK.

24.10.2020 [[https://www.youtube.com/watch?v=NpMWDCX1yMI][Robert F. Kennedy, Jr.: Int'l. Message for Freedom and Hope]] (Youtube)

Calls Corona epidemic a global Coup d'etat by Big Data and other companies led
by Bill Gates.

** Die Maßnahmen

*** Ignorieren von Gerichtsurteilen

Von Gerichten gekippte Maßnahmen werden in gleicher Form wieder verabschiedet.

- Beherbergungsverbot
  https://www.tagesschau.de/inland/beherbergungsverbot-brandenburg-103.html
- Sperrstunden
  https://www.sr.de/sr/home/nachrichten/politik_wirtschaft/gericht_kippt_sperrstunde_saarland_100.html

*** Lockdown

Film "Unerhört!", Prof. Michael Levitt, Nobelpreisträger für Chemie, Stanford
Universität [ab Minute 29, transkribiert]: “Es gibt ein weiteres Risiko:
Rezessionen töten Menschen. Bei einer Rezession steigt die Sterberate. Eine
harte Rezession ist sicher gefährlicher als Covid-19. […] Lockdown klingt gut,
aber die WHO hat ihn nie empfohlen. Es ist eine mittelalterliche Maßnahme,
recht primitiv. Besser ist, den Menschen zu sagen, haltet Abstand, mindestens
drei Meter. Und wenn sich die Lage verbessert, zwei Meter, eineinhalb…”

*** Maskenpflicht

Es gibt große Variationen in der Wirksamkeit zwischen Stoffmasken und
medizinischen Masken. Trotzdem wird ohne weitere Differenzierung nur eine
Mund-Nasen-Bedeckung gefordert. Ein Infektionsschutz kann also nicht der
Hauptzweck der Maskenpflicht sein.

Das Bundesinstitut für Arzneimittel und Medizinprodukte [[https://www.bfarm.de/SharedDocs/Risikoinformationen/Medizinprodukte/DE/schutzmasken.html][schreibt]] über
nicht-medizinische Stoffmasken: "Träger der beschriebenen
Mund-Nasen-Bedeckungen können sich nicht darauf verlassen, dass diese sie oder
andere vor einer Übertragung von SARS-CoV-2 schützen, da für diese Masken
keine entsprechende Schutzwirkung nachgewiesen wurde." und weiter: "Trotz
dieser Einschränkungen können geeignete Masken als Kleidungsstücke dazu
beitragen, die Geschwindigkeit des Atemstroms oder Tröpfchenauswurfs z.B. beim
Husten zu reduzieren. Auf diese Weise können sie bzw. ihre Träger einen
Beitrag zur Reduzierung der weiteren Ausbreitung von SARS-CoV-2 leisten."

Die Masken könnten also eventuell andere schützen obwohl dies zwei Absätze
vorher als nicht nachgewiesen erklärt wurde.. Die gleiche, nicht nachgewiesene
aber vielleicht theoretisch denkbare Schutzwirkung ist aber wahrscheinlich
auch erreicht, wenn man einfach in seine Armbeuge hustet. Es ist absolut nicht
nachvollziehbar, dass die Maske bei ruhig auf ihrem Stuhl sitzenden Schülern
mit ruhigem Atem irgendeine messbare Wirkung hätte.

- [[https://www.thieme-connect.com/products/ejournals/abstract/10.1055/a-1174-6591][Mund-Nasen-Schutz in der Öffentlichkeit: Keine Hinweise für eine
  Wirksamkeit]]. Krankenhaushygiene up2date 2020; 15(03): 279-295
- Prof. Dr. Christian Drosten am 30.1.2020, [[https://www.youtube.com/watch?v=Z3Zth7KYVHY&t=1556][Youtube, ab 25:56]]:
  - Interviewer: "Sie können die Maske aufsetzen"
  - Drosten: "Damit hält man das nicht auf. [...] Können wir noch einmal
    separat drüber reden, aber die technischen Daten dazu sind nicht gut, für
    das Aufhalten mit der Maske."
- Vizepräsident des Robert-Koch-Instituts, Prof. Dr. Lars Schaade, am
  28.02.2020, [[https://www.youtube.com/watch?v=AsQW0AVbTNo&t=300][Youtube, ab 5:00]]:
  - 5:00 Masken werden nicht empfohlen, auch Desinfektionsmittel nicht
  - 14:00 "Meine Einschätzung wäre, dass sich das in etwa bewegt in der Stärke
    wie eine starke bis sehr starke Grippewelle.
  - 17:45 "Die Masken… das ist mehrfach untersucht worden. Es gibt einfach
    keine wissenschaftliche Evidenz, dass das irgendeinen Sinn hätte"
- Eine interne Hausmitteilung des Deutschen Bundestages warnt vor der
  signifikanten CO2-Anreicherung im Blut bei längerem Maskentragen. (TODO:
  link, Hausmitteilung 222/2020; Deutscher Bundestag; 28.08.2020)

*** Schulschließungen

*** Reisebeschränkungen

*** Maßnahmen die nicht diskutiert wurden

- Maßnahmen zur Stärkung des Immunsystems, z.B. Arbeitszeitreduktion
- Erhöhung des Pflegepersonals
- Spaziergänge an der frischen Luft
- Besondere Ladenöffnungszeiten für alte Menschen

*** Corona-App

"Die Corona-Warn-App bleibt weit unter ihren Möglichkeiten, sie muss weiter
entwickelt werden und müsse bussgeldbewährt zur Pflicht werden." - Thomas
Röwekamp, Fraktionsvorsitzender CDU, Bremen. [[https://www.weser-kurier.de/bremen/bremen-stadt_artikel,-bremer-cdu-fordert-pflicht-fuer-coronawarnapp-_arid,1941891.html][Weser Kurier]], 31.10.2020

*** Impfung

TODO!

- Es gibt verschiedene Arten von Impfstoffen, manche davon sehr neu,
  experimentell und vermutlich hochgefährlich. Bei der Impfung gegen die
  Schweinegrippe soll es viele schwere Impfschäden gegeben haben.

Siehe auch S.17 in "Wie-soll-es-weitergehen"

Es gab in der Humanmedizin bisher noch keinen zugelassenen Impfstoff gegen ein
Virus aus der Corona-Familie. Trotzdem sollen nun Impfstoffe in extrem
verkürzten Verfahren zugelassen werden.

Zum Thema Impfstoffe äußern sich z.B. [[https://www.clemensarvay.com][Clemens Arvay]], Sucharit Bhakdi, siehe
für beide auch die Literaturhinweise.

** Die Nebenwirkungen

Der Oberregierungsrat Stephan Kohn aus der Abteilung Krisenmanagement und
Bevölkerungsschutz des Innenministeriums ist bereits im Mai seiner Pflicht
nachgekommen und hat in dem Gutachten "[[https://www.freidenker.org/fw17/wp-content/uploads/2020/05/200508-BMI_KM4.pdf][Coronakrise 2020 aus Sicht des Schutzes
Kritischer Infrastrukturen]]" ausführlich die schädlichen Folgen der
Coronamaßnahmen beschrieben. Er ist für seine Pflicherfüllung diszipliniert
worden.

*** Tote in Entwicklungsländern

23.9.2020, Reuters: [[https://de.reuters.com/article/afrika-virus-m-ller-idDEKCN26E0MN][Entwicklungsminister - An Lockdown-Folgen sterben mehr
Menschen als am Virus]]: "Allein auf dem afrikanischen Kontinent rechnen wir
dieses Jahr mit zusätzlich 400.000 Malaria-Toten und HIV-Opfern sowie einer
halben Million mehr, die an Tuberkulose sterben werden."

* Ist es eine Pandemie?
** Sterblichkeit

Die WHO erklärt selber Anfang Oktober, dass bisher etwa 10% aller Menschen
weltweit inifziert wurden:
https://off-guardian.org/2020/10/08/who-accidentally-confirms-covid-is-no-more-dangerous-than-flu

"Our current best estimates tell us that about ten percent of the global
population may have been infected by this virus. This varies depending on
country, it varies from urban to rural, it varies between different groups." -
Dr. Michael Ryan, Executive Director, WHO Health Emergencies Programme

Global Deaths, 29.10.2020 gemäß Dashboard der Johns Hopkins Universität:
1,176,726
https://coronavirus.jhu.edu/map.html

Weltbevölkerung: 7,8 Milliarden Menschen

Dreisatz: 1.176.726 / (7,8E9 * 10%) = 0,15%

Sterblichkeit der gewöhnlichen Grippe (Influenza): 0,1% - 0,2%

https://de.wikipedia.org/wiki/Influenza#Todesf%C3%A4lle
https://www.helios-gesundheit.de/magazin/corona/news/corona-versus-grippe-was-ist-gefaehrlicher/

** Positivrate

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-08-26-de.pdf

Die Positivenquoten seit der Kalenderwoche 22 (25. Mai) sind:
1,06 0,94 0,86 1,37 0,79 0,61 0,59 0,65 0,79 0,98 1,00 0,97 0,88

Nach meinen Informationen liegt die Rate der falschen Positiven Testergebnisse
auch im Bereich von einem Prozent. Es ist also sehr abenteuerlich, mit solchen
Zahlen von einer Pandemie zu sprechen.

** Übersterblichkeit

*** Deutschland

https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/sterbefallzahlen.html

In der Übersicht der Einzeljahre sieht man deutlich, dass die Sterblichkeit in 2018 höher war:

https://www.destatis.de/DE/Themen/Querschnitt/Corona/_Grafik/_Interaktiv/woechentliche-sterbefallzahlen-jahre.html?nn=209016

*** Schweden

https://www.heise.de/tp/features/Macht-es-noch-einmal-Schweden-4944159.html
https://sebastianrushworth.com/2020/10/31/a-history-of-the-swedish-covid-response
https://www.nachdenkseiten.de/?p=66378
https://www.nachdenkseiten.de/?p=65143#h01

*** Weißrussland

Weißrussland hat keinerlei besondere Maßnahmen getroffen. Wenn es eine
Übersterblichkeit gäbe, würde die Opposition sie gegen den Präsidenten
verwenden. Von einem solchen Vorwurf ist allerdings nichts bekannt.

Der Weißrussische Präsident Lukaschenko [[https://corona-transition.org/weissrussland-ohne-lockdown-soll-das-land-keine-nothilfekredite-erhalten][behauptet]], der Internationale
Währungsfond (IMF) hätte dem Land einen Kredit nur bewilligen wollen, falls es
dort ebenfalls einen Lockdown gäbe. Dies sehen die Faktenchecker von [[https://correctiv.org/faktencheck/2020/08/27/nein-der-iwf-und-die-who-haben-belarus-keine-92-millionen-dollar-fuer-einen-lockdown-angeboten][Correctiv]]
und [[https://dpa-factchecking.com/germany/200819-99-222978][DPA]] anders.

Immerhin heißt es auf [[https://www.imf.org/en/About/FAQ/imf-response-to-covid-19][einer Webseite des IMF]]: "There are some requirements for
support [...], that it is pursuing broadly appropriate policies to address the
crisis (including safeguards to ensure that IMF funds are used for intended
purposes)." Das Wort "broadly" und die Klammer sind erst um den [[https://web.archive.org/web/20201102084407/https://www.imf.org/en/About/FAQ/imf-response-to-covid-19][2.11.2020]]
hinzugefügt worden.

*** Andere Länder

https://ourworldindata.org/excess-mortality-covid#excess-mortality-using-raw-death-counts

Die Grafiken zeigen, dass nicht alle Länder eine erhöhte Sterblichkeit in 2020 aufweisen.

10 Länder haben eine deutlich höhere Sterblichkeit für 2020: Belgium, Chile,
England & Wales, France, Italy, Netherlands, Scotland, Spain, Sweden, United
States

19 Länder haben keine höhere Sterblichkeit für 2020: Austria, Bulgaria,
Croatia, Czech Republic, Denmark, Estonia, Finland, Germany, Greece, Hungary,
Iceland, Israel, Latvia, Lithuania, Norway, Poland, Slovakia, Slovenia, South
Korea,

Für Portugal und die Schweiz ist der Graph nicht eindeutig. Wichtige Länder
fehlen auf der Seite: China, Russia, Belarus, Brasil, Venezuela, Australia.

* Was ist es dann?

** Das World Economic Forum

Das World Economic Forum (WEF) ist eine Art Dachverband der reichsten und
mächtigsten Menschen der Erde. Wichtige und bekannte Mitglieder sind vor
allem:

- Bill Gates, lange reichster Mensch, nun die Nr. 2 nach Jeff Bezos. 98
  Milliarden US-Dollar
- Warren Buffet, 67,5 Milliarden. Unterstützer der Bill und Melinda Gates
  Foundation
- George Soros, nur 8,6 Milliarden aber Gründer der einflußreichen Open
  Society Foundation

Weitere Gönner des WEF:
https://www.weforum.org/agenda/2015/10/the-20-most-generous-people-in-the-world

Das WEF versteht sich als Netzwerk zur Verbesserung der Welt. So hat man dort
auch Greta Thunberg eingeladen. Die Reichen sind sich der vielfältigen
Probleme der Welt sehr bewusst und wollen diese auch lösen. Allerdings wollen
sie diejenigen sein, die über die Lösung entscheiden. Dann können sie auch
sicherstellen, dass ihnen die Lösung nicht wehtut. Besser noch, sie können
Lösungen umsetzen, von denen sie profitieren.

Das Thema der Weltrettung ist "Stakeholder Value statt Shareholder Value". In
der alten Vorstellung des Shareholder Values (Interessen der Aktienbesitzer)
orientiert sich ein Unternehmen ausschließlich am finanziellen Gewinn.

Ein Stakeholder ist dagegen jeder, der ein Interesse an dem Unternehmen und
dessen Geschäftsfeld hat. Das schließt die Mitarbeiter und Kunden ein. Bei
internationalen Großkonzernen wie Amazon, Google oder Facebook dagegen sind
alle Menschen die Stakeholder.

Man könnte sich nun naiv darüber freuen, dass Unternehmen sich nicht mehr nur
am finanziellen Gewinn orientieren wollen. In der Realität allerdings
beanspruchen die Unternehmen nun die Entscheidungsbefugnis über alle Bereiche
der Gesellschaft, weit über ihr eigenes Unternehmen hinaus.

Siehe den Bericht des Deutschlandfunk zur Eröffnung des WEF in Davos am
20.1.2020: "[[https://www.deutschlandfunkkultur.de/stakeholder-value-und-shareholder-value-sind-kein.1008.de.html?dram:article_id=161716][Von der Verantwortung der Unternehmen Allgemeinwohl
vs. Aktionärswohl]]"

Das WEF hat eine umfangreiche Webseite unter dem Titel "[[https://www.weforum.org/great-reset][The Great Reset]]" (Der
große Neustart) veröffentlicht, dass für viele Bereiche aufzeigt, wie die neue
Welt aussehen soll. Die Ankündigung vom 3.6.2020 trägt den Titel "[[https://www.weforum.org/agenda/2020/06/now-is-the-time-for-a-great-reset][Jetzt ist
die Zeit für den großen Neustart]]". Es ist erstaunlich, dass das WEF in so
kurzer Zeit bereits ein Programm entwickelt, abgestimmt und mit einer extra
programmierten Webseite veröffentlicht hat. Schließlich konnte man frühestens
mit dem Lockdown Ende März davon ausgehen, dass es zu einer großen Krise käme.

** ID2020 / Digital Identity Alliance

https://id2020.org

Alle Menschen sollen eine weltweit eindeutige, zentral verwaltete digitale
Identität erhalten, die mit allen ihren wichtigen Daten verknüft wird.

- 2020-10-19: Kommt die überwachte Gesellschaft? deutschlandfunkkultur.de
  https://www.deutschlandfunkkultur.de/digitale-identitaet-kommt-die-ueberwachte-gesellschaft.976.de.html?dram:article_id=486012
- Mitglieder: Microsoft, Rockefeller Foundation, Gavi (The Vaccine Alliance),
  Mastercard, Care.org, ...
- 2020-03-24, Bill Gates: 33:25 “Eventually, what we'll have to have is
  certificates of who is a recovered person, who is a vaccinated person,
  because you don't want people moving around the world -- where you'll have
  some countries that won't have it under control, sadly -- you don't want to
  completely block off the ability for those people to go there and come back
  and move around.”
  https://www.ted.com/talks/bill_gates_how_we_must_respond_to_the_coronavirus_pandemic/transcript
- SRF: Globale E-ID Initiativen – ihre Möglichkeiten und Grenzen. Podcast
  https://www.srf.ch/play/radio/kontext/audio/globale-e-id-initiativen---ihre-moeglichkeiten-und-grenzen?id=83db5967-74ff-4cf7-b22a-d7aa7ee712e5
- Norbert Häring: Hörempfehlung: Bericht des Schweizer Rundfunks über ID2020, Known Traveller und Co.
  https://norberthaering.de/die-regenten-der-welt/srf-id2020

** Better Than Cash initiative

https://betterthancash.org

Mitglieder: Bill & Melinda Gates Foundation, Care.org, Clinton Development
Initiative, Mastercard, … (75 total)

Die Initiative bemüht sich um die Verdrängung des Bargelds durch digitale
Zahlungsmittel. Dies erlaubt eine weitere Überwachung und wiederum neue
Geschäftsfelder auf Basis der gewonnenen Daten.

** The Commons Project

Die Webseite [[https://thecommonsproject.org][thecommonsproject.org]] enthält keine Informationen über die
Finanzierung außer einem Hinweis auf der Startseite: "The Commons Project was
established with support from the Rockefeller Foundation." Trotzdem arbeitet
diese Organisation an vier Projekten mit globaler Reichweite und sicherlich
hohen Entwicklungskosten.

*** CommonPass

Das [[https://thecommonsproject.org/commonpass][CommonPass Project]] befindet sich seit Oktober in der Testphase, wie
aero.de am 12.10.2020 berichtet: [[https://www.aero.de/news-37215/CommonPass-soll-internationales-Reisen-wieder-ermoeglichen.html]["CommonPass" soll internationales Reisen
wieder ermöglichen.]]  Mithilfe des CommonPass können Länder effizient
Einreisebeschränkungen umsetzen. Nur wer mithilfe eines auf seinem Smartphone
hochgeladenen negativen Testresultat oder eines Impfnachweises seine
Ungefährlichkeit nachweisen kann, darf einreisen.

Das WEF bewirbt den CommonPass auf seiner Covid-Action Plattform:
[[https://www.weforum.org/projects/commonpass][weforum.org/projects/commonpass]].

*** CommonHealth

Mithilfe der [[https://thecommonsproject.org/commonhealth][CommonHealth]] App kann jeder Mensch alle seine
Gesundheitsinformationen bequem in die Cloud laden und jederzeit mit jedem
Teilen, der danach fragt.

Die einfache Verfügbarkeit von Gesundheitsinformationen weckt natürlich auch
Begehrlichkeiten von Arbeitgebern oder Krankenversicherungen. Versicherungen
werden zunächst auf freiwilliger Basis günstigere Tarife anbieten, wenn der
Kunde alle seine Krankenakten teilt. Heute schon bietet mir meine
Krankenversicherung einen Teledoktor an. Würde ich mich verpflichten, mich
immer zuerst bei der Hotline der Krankenkasse beraten zu lassen, so könnte ich
von einem günstigeren Tarif profitieren.

Auch Pharmakonzerne haben natürlich ein großes Interesse an den digitalen
Gesundheitsdaten. Schon heute bekommen Konzerne in Deutschland Zugriff auf die
pseudonymisierten Daten der verpflichtenden Gesundheitskarte: Nachdenkseiten,
20.8.2020, [[https://www.nachdenkseiten.de/?p=63919][Der Türöffner: Wie Jens Spahn den gläsernen Patienten
herbeiregiert]].

*** COVIDcheck

TODO: https://thecommonsproject.org/covidcheck

*** CommonGEO

TODO: https://thecommonsproject.org/commongeo

** Aber warum liest und hört man nichts?

- Millionenhilfe für Verlage -
  Deutschland steigt in die direkte Presseförderung ein
  https://www.deutschlandfunk.de/millionenhilfe-fuer-verlage-deutschland-steigt-in-die.2907.de.html?dram:article_id=486614
- Spenden der Bill und Melinda Gates Foundation an Verlage
  - Spiegel Online, 2018, $2,537,294
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database/Grants/2018/12/OPP1203082
  - Guardian News & Media Ltd, 2011-2020, ca $14.5 Millionen
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database#q/k=guardian
  - Financial Times Ltd, $503,341 + $1,344,444 + $462,060
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database/Grants/2015/11/OPP1134848
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database/Grants/2016/11/OPP1161256
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database/Grants/2020/10/INV-019471
  - Solutions Journalism Network Inc
    https://www.gatesfoundation.org/How-We-Work/Quick-Links/Grants-Database/Grants/2018/09/OPP1195811
- "Google hat den europäischen Journalismus seit 2013 mit mehr als 200
  Millionen Euro gefördert."
  https://www.diepresse.com/5888372/200-millionen-euro-von-google-fur-journalismus-in-europa
  "Inzwischen ist die News Initiative sogar ein weltweites Unterfangen,
  ausgestattet mit weiteren 300 Millionen Dollar."
  https://netzpolitik.org/2020/wie-der-datenkonzern-den-journalismus-umgarnt/

Medien versagen regelmäßig bei entscheidenden Themen:

- Brutkastenlüge Irakkrieg 1
- Chemiewaffenlüge Irakkrieg 2
- Hufeisenplanlüge Kosovokrieg
- NATO Sichtweise zu Putschen oder Putschversuchen in Bolivien, Venezuela,
  Syrien, Ukraine, Weißrussland, Hongkong, ...
- Lügen zur angeblichen Notwendigkeit der privaten Altersvorsorge

** Aber es können doch nicht alle Wissenschaftler falsch liegen?

- Drittmittelabhängigkeit
- Ohne die BMGF geht im medizinischen Bereich weltweit nichts.
- Außerdem gibt es viele Wissenschaftler, die widersprechen, vor allem solche,
  die ihre Karriere hinter sich haben.

* Ausblick

Es ist zu hoffen, dass es dem Weltwirtschaftsforum nicht gelingt, seine Pläne
umzusetzen. Doch was dann? Sollten die Machtstrukturen bestehen bleiben, so
ist es nur eine Frage der Zeit, bis ein neuer Versuch gelingt.

Die Bürger der ehemaligen DDR haben erlebt, wie eine euphorische Wendezeit
schnell in eine Entäuschung umschlug.

Der Aufbau von Neuem benötigt ein stabiles Fundament aus Wissen, Haltung und
Gemeinschaft. Wer möchte an diesem Fundament mitarbeiten?

- Was ist der Mensch?
- Was ist die Würde des Menschen?
- Was ist christliche Lebenshaltung? (Erst wenn wir über unseren eigenen
  kulturellen Hintergrund und unsere Prägung wissen, können wir tatsächlich
  fremde Kulturen würdigen.)

Hauke Ritz, 31.10.2020 [[https://multipolar-magazin.de/artikel/chance-fur-humanismus][Die Krise des Westens: Chance für einen neuen Humanismus?]]

#+BEGIN_EXPORT latex
\newlength{\saveleftmargini}
\setlength{\saveleftmargini}{\leftmargini}
\setlength{\leftmargini}{10em}
#+END_EXPORT
#+BEGIN_VERSE
Wer nicht von dreitausend Jahren
sich weiß Rechenschaft zu geben,
bleib im Dunkeln unerfahren,
mag von Tag zu Tage leben.
#+END_VERSE
#+LATEX: \setlength{\leftmargini}{\saveleftmargini}

* Weitere Links

- https://swprs.org/fakten-zu-covid-19
- https://corona-ausschuss.de
- Unerhört! Film: https://vimeo.com/471959768
  - Das volle Interview mit dem spanischen Krankenhausarzt
    https://www.youtube.com/watch?v=wl9h-7MaLws
- https://www.ckb-anwaelte.de/blog
- https://elternstehenauf.de
- https://www.initiative-corona.info
- Film: Profiteure der Angst. Arte Doku
  https://www.youtube.com/watch?v=ZkyL4NxJJcc
  https://www.youtube.com/watch?v=1wP4-Z_lvyE
  Kurzfassung: https://www.youtube.com/watch?v=vCz34z3ymyY
- http://www.aerzteklaerenauf.de
- https://www.ärzte-für-aufklärung.de
- https://wie-soll-es-weitergehen.de - Sebastian Friebel,
  Ehem. parlamentarischer Berater des Deutschen Bundestages. Die meisten
  Aussagen seines Dokumentes finden sich auch in dieser
  Zusammenstellung. Leider sind die Quellennachweise seines Dokumentes keine
  vollständigen URLs.
- https://www.corona-experten.de - TODO noch zu prüfen!

* Weitere Themen
** Epidemien als Folge des Neoliberalismus

Der Freitag, 2.11.2020: [[https://www.freitag.de/autoren/der-freitag/wir-koennen-einpacken?][„Wir können einpacken!“]] - "Die Corona-Pandemie hängt
eng mit dem Kapitalismus, der Agrar-Industrie und dem Raubbau an der Natur
zusammen, sagt der Epidemiologe und Biologe Rob Wallace"

* Literatur

- Paul Schreyer: [[https://www.westendverlag.de/buch/chronik-einer-angekuendigten-krise][Chronik einer angekündigten Krise]] (Spiegel Bestseller)
- [[https://mediashop.at/buecher/lockdown-2020][Lockdown 2020]], Besprechung [[https://www.nachdenkseiten.de/?p=65867][Nachdenkseiten]], [[https://www.nachdenkseiten.de/?p=65968][Interview]]
- Karina Reiß und Sucharit Bhakdi: Corona Fehlalarm? Daten, Fakten,
  Hintergründe. Goldegg Verlag, Berlin/Wien 2020, ISBN 978-3-99060-191-4 (159
  S.). [[https://de.wikipedia.org/wiki/Corona_Fehlalarm%3F][Wikipedia]] (Spiegel Bestseller)
- Clemens G. Arvay: Wir können es besser (Spiegel Bestseller)
- Wolfgang Kubicki: Meinungsunfreiheit (Spiegel Bestseller)

* Humor

- Die Echse über Sicherheitsmaßnahmen im Tierreich [[https://www.youtube.com/watch?v=zg3rV_vZmsU][YT]]
- Die Echse spielt die Coronakrise mit Enten nach [[https://www.youtube.com/watch?v=M8cBaXL3QOI&t=1s][YT]]
- Corona Song von Dieter Hallervorden [[https://www.youtube.com/watch?v=k4OFXkcn24Q][YT]]
- Drosten-Impfung mit Nebenwirkung: Simone Solga träumt von Steinmeier! [[https://www.youtube.com/watch?v=gLtXT7jAhk4][YT]]

# Local Variables:
# org-latex-hyperref-template: "\\hypersetup{ pdftitle={Corona Reader}, colorlinks=true }\n"
# End:
